export const actionTypes = {
  GET_SHOP: "GET_SHOP",
  ADD_TO_CART: "ADD_TO_CART",
  OPEN_CART: "OPEN_CART",
  REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
  DELETE_ITEM: "DELETE_ITEM",
  DELETE_CART: "DELETE_CART",
  SAVE_ORDER: "SAVE_ORDER",
  SEND_ORDER: "SEND_ORDER",
  TOGGLE_SEARCH_MODAL: "TOGGLE_SEARCH_MODAL",
  VALIDATE_PAYMENT: "VALIDATE_PAYMENT",
  CONFIRM_SUCCESS: "CONFIRM_SUCCESS",
};
